soes_state:
  ros__parameters:
    pump_on_s: 2.0
    settle_s: 0.5
    order: [1, 0, 2]          # center, left, right (indices your motion node expects)
    roller_distance_mm: 100.0
    roller_speed_mm_s: 40.0
    camera_timeout_s: 2.0
